# Generated by Django 5.2.dev20241105155934 on 2024-11-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0002_alter_masterinstrument_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masterinstrument',
            table='master_instruments',
        ),
    ]
