# Generated by Django 5.2.dev20241105155934 on 2024-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExchangeSegment', models.CharField(max_length=255)),
                ('ExchangeInstrumentID', models.CharField(max_length=255)),
                ('InstrumentType', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Series', models.CharField(max_length=255)),
                ('NameWithSeries', models.CharField(max_length=255)),
                ('InstrumentID', models.CharField(max_length=255)),
                ('PriceBandHigh', models.FloatField()),
                ('PriceBandLow', models.FloatField()),
                ('FreezeQty', models.IntegerField()),
                ('TickSize', models.FloatField()),
                ('LotSize', models.IntegerField()),
                ('Multiplier', models.FloatField()),
                ('UnderlyingInstrumentId', models.CharField(max_length=255)),
                ('UnderlyingIndexName', models.CharField(max_length=255)),
                ('ContractExpiration', models.DateField()),
                ('StrikePrice', models.FloatField()),
                ('OptionType', models.CharField(max_length=255)),
            ],
        ),
    ]
