# Generated by Django 5.2.dev20241105155934 on 2024-11-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterinstrument',
            options={'managed': False},
        ),
    ]
